defmodule Yog.IO.MatrixMarket do
  @moduledoc """
  Matrix Market (.mtx) format serialization support.

  Provides functions to serialize and deserialize graphs in the Matrix Market
  exchange format, a common format for sharing sparse and dense matrices in
  scientific computing and graph theory.

  ## Format Overview

  Matrix Market files start with a header:
  `%%MatrixMarket matrix <format> <field> <symmetry>`

  - **Format**: `coordinate` (sparse) or `array` (dense) - Currently `coordinate` is primary.
  - **Field**: `real`, `integer`, `pattern`, or `complex`.
  - **Symmetry**: `general`, `symmetric`, `skew-symmetric`, or `hermitian`.

  For graph representation:
  - Rows and Columns represent nodes.
  - Matrix indices are **1-based**.
  - Symmetric matrices are often used for undirected graphs.

  ## Example

      iex> graph = Yog.directed()
      ...> |> Yog.add_node(1, nil)
      ...> |> Yog.add_node(2, nil)
      ...> |> Yog.add_edge_ensure(from: 1, to: 2, with: 5.0)
      iex>
      iex> mtx_string = Yog.IO.MatrixMarket.serialize(graph)
      iex> String.contains?(mtx_string, "%%MatrixMarket matrix coordinate real general")
      true
      iex> String.contains?(mtx_string, "1 2 5.0")
      true

  ## Default Configurations

  Default behavior:
  - Node data: Ignored during serialization (Matrix Market only stores matrix values)
  - Edge weights: Converted to float or integer
  """

  alias Yog.Model

  @doc """
  Returns default Matrix Market serialization options.

  - `weight_formatter` - Function to convert edge weights to strings (default: `&Yog.Utils.to_weight_label/1`)
  - `edge_formatter`: `Yog.Utils.safe_string/1`
  - `node_formatter`: `Yog.Utils.safe_string/1`
  """
  @spec default_options() :: tuple()
  def default_options do
    {:matrix_market_options, &Yog.Utils.to_weight_label/1, &Yog.Utils.safe_string/1,
     &Yog.Utils.safe_string/1}
  end

  @doc """
  Creates Matrix Market options with custom configurations.

  Raises `ArgumentError` if `weight_formatter` is not an arity-1 function or `opts` is invalid.
  """
  @spec options_with((any() -> any()), keyword()) :: tuple()
  def options_with(weight_formatter, opts \\ []) do
    if not is_function(weight_formatter, 1) do
      raise ArgumentError, "expected weight_formatter to be an arity-1 function"
    end

    if not Keyword.keyword?(opts) do
      raise ArgumentError, "expected opts to be a keyword list, got: #{inspect(opts)}"
    end

    node_fmt = Keyword.get(opts, :node_formatter, &Yog.Utils.safe_string/1)
    edge_fmt = Keyword.get(opts, :edge_formatter, &Yog.Utils.safe_string/1)

    if not is_function(node_fmt, 1) do
      raise ArgumentError, "expected node_formatter to be an arity-1 function"
    end

    if not is_function(edge_fmt, 1) do
      raise ArgumentError, "expected edge_formatter to be an arity-1 function"
    end

    {:matrix_market_options, weight_formatter, edge_fmt, node_fmt}
  end

  @doc """
  Serializes a graph to Matrix Market coordinate format.

  Raises `ArgumentError` if `graph` is not a `Yog.Graph` or `Yog.DAG` struct.

  Time complexity: $\\mathcal{O}(V + E)$ where $V$ is node count and $E$ is edge count.

  ## Example

      iex> graph = Yog.directed()
      ...> |> Yog.add_node(1, nil)
      ...> |> Yog.add_node(2, nil)
      ...> |> Yog.add_edge_ensure(from: 1, to: 2, with: 1.5)
      iex> mtx = Yog.IO.MatrixMarket.serialize(graph)
      iex> String.contains?(mtx, "1 2 1.5")
      true
  """
  @spec serialize(Yog.graph()) :: String.t()
  def serialize(graph) do
    serialize_with(default_options(), graph)
  end

  @doc """
  Serializes a graph to Matrix Market format with custom options.

  Raises `ArgumentError` if `options` or `graph` are invalid.

  Time complexity: $\\mathcal{O}(V + E)$ where $V$ is node count and $E$ is edge count.
  """
  @spec serialize_with(tuple(), Yog.graph()) :: String.t()
  def serialize_with(options, graph) do
    unless is_struct(graph, Yog.Graph) or is_struct(graph, Yog.DAG) do
      raise ArgumentError, "expected a Yog.Graph or Yog.DAG struct, got: #{inspect(graph)}"
    end

    {weight_fmt, node_fmt, edge_fmt} =
      case options do
        {:matrix_market_options, wf, ef, nf}
        when is_function(wf, 1) and is_function(ef, 1) and is_function(nf, 1) ->
          {wf, nf, ef}

        {:matrix_market_options, wf} when is_function(wf, 1) ->
          {wf, &Yog.Utils.safe_string/1, &Yog.Utils.safe_string/1}

        _ ->
          raise ArgumentError, "expected valid options tuple, got: #{inspect(options)}"
      end

    type = Model.type(graph)
    node_count = Model.order(graph)
    edges = Model.all_edges(graph)
    edge_count = length(edges)

    symmetry = if type == :directed, do: "general", else: "symmetric"

    header = "%%MatrixMarket matrix coordinate real #{symmetry}\n"
    comment = "% Generated by Yog\n"
    size_line = "#{node_count} #{node_count} #{edge_count}\n"

    data_lines =
      edges
      |> Enum.map_join("\n", fn {from, to, weight} ->
        w_str = weight_fmt.(weight)
        "#{node_fmt.(from)} #{node_fmt.(to)} #{edge_fmt.(w_str)}"
      end)

    [header, comment, size_line, data_lines, ""]
    |> Enum.join("")
  end

  @doc """
  Writes a graph to a Matrix Market file.

  Raises `ArgumentError` if `path` is not a binary string or `graph` is invalid.
  """
  @spec write(String.t(), Yog.graph()) :: :ok | {:error, atom()}
  def write(path, graph) when is_binary(path) do
    content = serialize(graph)
    File.write(path, content)
  end

  def write(path, _graph) do
    raise ArgumentError, "expected path to be a binary string, got: #{inspect(path)}"
  end

  @doc """
  Writes a graph to a Matrix Market file with custom options.

  Raises `ArgumentError` if `path` is not a binary string or options/graph are invalid.
  """
  @spec write_with(String.t(), tuple(), Yog.graph()) :: :ok | {:error, atom()}
  def write_with(path, options, graph) when is_binary(path) do
    content = serialize_with(options, graph)
    File.write(path, content)
  end

  def write_with(path, _options, _graph) do
    raise ArgumentError, "expected path to be a binary string, got: #{inspect(path)}"
  end

  @doc """
  Parses a Matrix Market string into a graph.

  Raises `ArgumentError` if `input` is not a binary string or `g_type` is invalid.

  Time complexity: $\\mathcal{O}(V + E)$ where $V$ is node count and $E$ is edge count.

  ## Parameters

  - `input`: Matrix Market format string
  - `g_type`: `:directed` or `:undirected` (overrides header symmetry if provided)

  ## Returns

  - `{:ok, {:matrix_market_result, graph, warnings}}` on success
  - `{:error, reason}` on parsing failure
  """
  @spec parse(String.t(), atom() | nil) ::
          {:ok, {:matrix_market_result, Yog.graph(), list()}} | {:error, term()}
  def parse(input, g_type \\ nil)

  def parse(input, g_type) when is_binary(input) do
    parse_with(input, g_type, fn id -> id end, fn w -> w end)
  end

  def parse(input, _g_type) do
    raise ArgumentError, "expected input to be a binary string, got: #{inspect(input)}"
  end

  @doc """
  Parses a Matrix Market string with custom node and edge parsers.

  Raises `ArgumentError` if `input` is not a binary string or parsers/g_type are invalid.

  Time complexity: $\\mathcal{O}(V + E)$ where $V$ is node count and $E$ is edge count.
  """
  @spec parse_with(String.t(), atom() | nil, (any() -> any()), (any() -> any())) ::
          {:ok, {:matrix_market_result, Yog.graph(), list()}} | {:error, term()}
  def parse_with(input, g_type, node_parser, edge_parser) when is_binary(input) do
    if g_type != nil and g_type not in [:directed, :undirected] do
      raise ArgumentError, "Invalid graph type: #{inspect(g_type)}"
    end

    if not is_function(node_parser, 1) do
      raise ArgumentError, "expected node_parser to be an arity-1 function"
    end

    if not is_function(edge_parser, 1) do
      raise ArgumentError, "expected edge_parser to be an arity-1 function"
    end

    if String.trim(input) == "" do
      {:error, :empty_input}
    else
      lines = String.split(input, "\n", trim: false)
      parse_lines(lines, g_type, node_parser, edge_parser)
    end
  end

  def parse_with(input, _g_type, _node_parser, _edge_parser) do
    raise ArgumentError, "expected input to be a binary string, got: #{inspect(input)}"
  end

  @doc """
  Reads a graph from a Matrix Market file.

  Raises `ArgumentError` if `path` is not a binary string.
  """
  @spec read(String.t(), atom() | nil) ::
          {:ok, {:matrix_market_result, Yog.graph(), list()}} | {:error, term()}
  def read(path, g_type \\ nil)

  def read(path, g_type) when is_binary(path) do
    case File.read(path) do
      {:ok, content} -> parse(content, g_type)
      {:error, _} = error -> error
    end
  end

  def read(path, _g_type) do
    raise ArgumentError, "expected path to be a binary string, got: #{inspect(path)}"
  end

  @doc """
  Reads a graph from a Matrix Market file with custom parsers.

  Raises `ArgumentError` if `path` is not a binary string.
  """
  @spec read_with(String.t(), atom() | nil, (any() -> any()), (any() -> any())) ::
          {:ok, {:matrix_market_result, Yog.graph(), list()}} | {:error, term()}
  def read_with(path, g_type, node_parser, edge_parser) when is_binary(path) do
    case File.read(path) do
      {:ok, content} -> parse_with(content, g_type, node_parser, edge_parser)
      {:error, _} = error -> error
    end
  end

  def read_with(path, _g_type, _node_parser, _edge_parser) do
    raise ArgumentError, "expected path to be a binary string, got: #{inspect(path)}"
  end

  # Private functions

  defp parse_lines(lines, g_type, node_parser, edge_parser) do
    with {:ok, header, rest} <- parse_header(lines),
         {:ok, size, rest} <- parse_size(rest),
         {:ok, graph, edge_warnings} <-
           build_graph(rest, header, size, g_type, node_parser, edge_parser) do
      {:ok, {:matrix_market_result, graph, edge_warnings}}
    else
      {:error, _} = error -> error
    end
  end

  defp parse_header([line | rest]) do
    trimmed = String.trim(line)

    if String.starts_with?(trimmed, "%%MatrixMarket") do
      parts = String.split(trimmed, ~r/\s+/)

      case parts do
        ["%%MatrixMarket", "matrix", format, field, symmetry] ->
          {:ok, %{format: format, field: field, symmetry: symmetry}, rest}

        _ ->
          {:error, {:invalid_header, line}}
      end
    else
      {:error, {:missing_header, line}}
    end
  end

  defp parse_header([]), do: {:error, :empty_input}

  defp parse_size([line | rest]) do
    trimmed = String.trim(line)

    cond do
      trimmed == "" ->
        parse_size(rest)

      String.starts_with?(trimmed, "%") ->
        parse_size(rest)

      true ->
        case String.split(trimmed, ~r/\s+/) do
          [rows, cols, entries] ->
            with {r, ""} <- Integer.parse(rows),
                 {c, ""} <- Integer.parse(cols),
                 {e, ""} <- Integer.parse(entries) do
              {:ok, %{rows: r, cols: c, entries: e}, rest}
            else
              _ -> {:error, {:invalid_size_line, line}}
            end

          _ ->
            {:error, {:invalid_size_line, line}}
        end
    end
  end

  defp parse_size([]), do: {:error, :unexpected_end_of_file}

  defp build_graph(lines, header, size, g_type, node_parser, edge_parser) do
    final_type =
      cond do
        g_type != nil -> g_type
        header.symmetry in ["symmetric", "skew-symmetric", "hermitian"] -> :undirected
        true -> :directed
      end

    base_graph = Model.new(final_type)
    max_node = max(size.rows, size.cols)

    graph =
      if max_node > 0 do
        Enum.reduce(1..max_node, base_graph, fn id, g ->
          Model.add_node(g, id, node_parser.(id))
        end)
      else
        base_graph
      end

    parse_edge_lines(lines, graph, header, edge_parser, [])
  end

  defp parse_edge_lines([], graph, _header, _edge_parser, warnings) do
    {:ok, graph, Enum.reverse(warnings)}
  end

  defp parse_edge_lines([line | rest], graph, header, edge_parser, warnings) do
    trimmed = String.trim(line)

    cond do
      trimmed == "" ->
        parse_edge_lines(rest, graph, header, edge_parser, warnings)

      String.starts_with?(trimmed, "%") ->
        parse_edge_lines(rest, graph, header, edge_parser, warnings)

      true ->
        case parse_edge_line(trimmed, header, edge_parser) do
          {:ok, from, to, weight} ->
            case Model.add_edge(graph, from, to, weight) do
              {:ok, new_graph} ->
                parse_edge_lines(rest, new_graph, header, edge_parser, warnings)

              {:error, reason} ->
                parse_edge_lines(rest, graph, header, edge_parser, [
                  {:edge_add_failed, reason, line} | warnings
                ])
            end

          {:warning, warning} ->
            parse_edge_lines(rest, graph, header, edge_parser, [warning | warnings])
        end
    end
  end

  defp parse_edge_line(line, header, edge_parser) do
    parts = String.split(line, ~r/\s+/)

    case parts do
      [from_str, to_str | weight_parts] ->
        with {from, ""} <- Integer.parse(from_str),
             {to, ""} <- Integer.parse(to_str) do
          weight_val =
            case {header.field, weight_parts} do
              {"pattern", _} ->
                1.0

              {"real", [w | _]} ->
                parse_float(w)

              {"integer", [w | _]} ->
                parse_int(w)

              {"complex", [r, i | _]} ->
                {parse_float(r), parse_float(i)}

              {"complex", _} ->
                {:warning, {:incomplete_complex_line, line}}

              {_, [w | _]} ->
                w

              _ ->
                1.0
            end

          case weight_val do
            {:warning, _} = warning -> warning
            val -> {:ok, from, to, edge_parser.(val)}
          end
        else
          _ -> {:warning, {:invalid_edge_line, line}}
        end

      _ ->
        {:warning, {:invalid_edge_line, line}}
    end
  end

  defp parse_float(str) do
    case Float.parse(str) do
      {f, _} ->
        f

      :error ->
        str
    end
  end

  defp parse_int(str) do
    case Integer.parse(str) do
      {i, _} -> i
      :error -> str
    end
  end
end
